#### Churn - Taxa de Evasão dos Clientes

## Importando Dados

In [1]:
import pandas as pd

In [2]:
dados = pd.read_csv('./Dados/Customer-Churn.csv')

In [3]:
dados.shape #(linhas, colunas)

(7043, 18)

In [4]:
dados.head()

Maior65Anos Conjuge Dependentes  MesesDeContrato TelefoneFixo   
0            0     Sim         Nao                1          Nao  \
1            0     Nao         Nao               34          Sim   
2            0     Nao         Nao                2          Sim   
3            0     Nao         Nao               45          Nao   
4            0     Nao         Nao                2          Sim   

  VariasLinhasTelefonicas ServicoDeInternet SegurancaOnline BackupOnline   
0    SemServicoTelefonico               DSL             Nao          Sim  \
1                     Nao               DSL             Sim          Nao   
2                     Nao               DSL             Sim          Sim   
3    SemServicoTelefonico               DSL             Sim          Nao   
4                     Nao       FibraOptica             Nao          Nao   

  SeguroNoDispositivo SuporteTecnico TVaCabo StreamingDeFilmes TipoDeContrato   
0                 Nao            Nao     Nao               Nao    Mensalmente  \
1                 Sim            Nao     Nao               Nao          UmAno   
2                 Nao            Nao     Nao               Nao    Mensalmente   
3                 Sim            Sim     Nao               Nao          UmAno   
4                 Nao            Nao     Nao               Nao    Mensalmente   

  PagamentoOnline FormaDePagamento  ContaMensal Churn  
0             Sim    ChequeDigital        29.85   Nao  
1             Nao      ChequePapel        56.95   Nao  
2             Sim      ChequePapel        53.85   Sim  
3             Nao    DebitoEmConta        42.30   Nao  
4             Sim    ChequeDigital        70.70   Sim

#### Variável Categórica - Agrupamento por características em comum, por valores qualitativos
#### Variável Numérica - Medida ou conjunto infinito de valores

## Diferentes Variáveis

In [5]:
# modificação de forma manual
traducao_dic = {'Sim' : 1,
                'Nao' : 0}

dadosmodificados = dados [['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn']].replace(traducao_dic)
dadosmodificados.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn
0        1            0             0                1      0
1        0            0             1                0      0
2        0            0             1                1      1
3        0            0             0                0      0
4        0            0             1                1      1

In [6]:
# transformação pelo get_dummies
dummie_dados = pd.get_dummies(dados.drop(['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn'], axis=1))
# junção dos dados transformados com os que já tinhamos
dados_final = pd.concat([dadosmodificados, dummie_dados], axis=1)

In [7]:
dados_final.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn  Maior65Anos   
0        1            0             0                1      0            0  \
1        0            0             1                0      0            0   
2        0            0             1                1      1            0   
3        0            0             0                0      0            0   
4        0            0             1                1      1            0   

   MesesDeContrato  ContaMensal  VariasLinhasTelefonicas_Nao   
0                1        29.85                        False  \
1               34        56.95                         True   
2                2        53.85                         True   
3               45        42.30                        False   
4                2        70.70                         True   

   VariasLinhasTelefonicas_SemServicoTelefonico  ...  StreamingDeFilmes_Nao   
0                                          True  ...                   True  \
1                                         False  ...                   True   
2                                         False  ...                   True   
3                                          True  ...                   True   
4                                         False  ...                   True   

   StreamingDeFilmes_SemServicoDeInternet  StreamingDeFilmes_Sim   
0                                   False                  False  \
1                                   False                  False   
2                                   False                  False   
3                                   False                  False   
4                                   False                  False   

   TipoDeContrato_DoisAnos  TipoDeContrato_Mensalmente  TipoDeContrato_UmAno   
0                    False                        True                 False  \
1                    False                       False                  True   
2                    False                        True                 False   
3                    False                       False                  True   
4                    False                        True                 False   

   FormaDePagamento_CartaoDeCredito  FormaDePagamento_ChequeDigital   
0                             False                            True  \
1                             False                           False   
2                             False                           False   
3                             False                           False   
4                             False                            True   

   FormaDePagamento_ChequePapel  FormaDePagamento_DebitoEmConta  
0                         False                           False  
1                          True                           False  
2                          True                           False  
3                         False                            True  
4                         False                           False  

[5 rows x 39 columns]

X = inputs (dados de entrada)
y = outputs (dados de saída)

In [8]:
#Dica
pd.set_option('display.max_columns', None)

In [9]:
dados_final.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn  Maior65Anos   
0        1            0             0                1      0            0  \
1        0            0             1                0      0            0   
2        0            0             1                1      1            0   
3        0            0             0                0      0            0   
4        0            0             1                1      1            0   

   MesesDeContrato  ContaMensal  VariasLinhasTelefonicas_Nao   
0                1        29.85                        False  \
1               34        56.95                         True   
2                2        53.85                         True   
3               45        42.30                        False   
4                2        70.70                         True   

   VariasLinhasTelefonicas_SemServicoTelefonico  VariasLinhasTelefonicas_Sim   
0                                          True                        False  \
1                                         False                        False   
2                                         False                        False   
3                                          True                        False   
4                                         False                        False   

   ServicoDeInternet_DSL  ServicoDeInternet_FibraOptica   
0                   True                          False  \
1                   True                          False   
2                   True                          False   
3                   True                          False   
4                  False                           True   

   ServicoDeInternet_Nao  SegurancaOnline_Nao   
0                  False                 True  \
1                  False                False   
2                  False                False   
3                  False                False   
4                  False                 True   

   SegurancaOnline_SemServicoDeInternet  SegurancaOnline_Sim   
0                                 False                False  \
1                                 False                 True   
2                                 False                 True   
3                                 False                 True   
4                                 False                False   

   BackupOnline_Nao  BackupOnline_SemServicoDeInternet  BackupOnline_Sim   
0             False                              False              True  \
1              True                              False             False   
2             False                              False              True   
3              True                              False             False   
4              True                              False             False   

   SeguroNoDispositivo_Nao  SeguroNoDispositivo_SemServicoDeInternet   
0                     True                                     False  \
1                    False                                     False   
2                     True                                     False   
3                    False                                     False   
4                     True                                     False   

   SeguroNoDispositivo_Sim  SuporteTecnico_Nao   
0                    False                True  \
1                     True                True   
2                    False                True   
3                     True               False   
4                    False                True   

   SuporteTecnico_SemServicoDeInternet  SuporteTecnico_Sim  TVaCabo_Nao   
0                                False               False         True  \
1                                False               False         True   
2                                False               False         True   
3                                False                True         True   
4                                False               False         

In [10]:
Xmaria = [[0,0,1,1,0,0,39.90,1,0,0,0,1,0,1,0,0,0,0,1,1,1,0,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,1]]

In [11]:
#ymaria = ?

In [12]:
# Divisão em inputs e outputs
X = dados_final.drop('Churn', axis=1)
y = dados_final['Churn']

In [13]:
# Biblioteca para padronizar os dados
from sklearn.preprocessing import StandardScaler

In [14]:
norm = StandardScaler()

X_normalizado = norm.fit_transform(X)
X_normalizado[0]

array([ 1.03453023, -0.65401193, -3.05401039,  0.8297975 , -0.43991649,
       -1.27744458, -1.16032292, -0.96332984,  3.05401039, -0.85417615,
        1.38171215, -0.88565976, -0.52592737,  1.00669571, -0.52592737,
       -0.63393298, -0.88361972, -0.52592737,  1.3782406 ,  1.12942721,
       -0.52592737, -0.72396752,  1.0138687 , -0.52592737, -0.63943864,
        1.2273572 , -0.52592737, -0.79013171,  1.23648892, -0.52592737,
       -0.79607014, -0.56297505,  0.90418382, -0.51424938, -0.52504733,
        1.40641839, -0.54480692, -0.5298852 ])

In [15]:
Xmaria_normalizado = norm.transform(pd.DataFrame(Xmaria, columns=X.columns))
Xmaria_normalizado

array([[-0.96662231, -0.65401193,  0.32743831,  0.8297975 , -0.43991649,
        -1.31816495, -0.82630172,  1.03806605, -0.32743831, -0.85417615,
        -0.72373975,  1.12910177, -0.52592737,  1.00669571, -0.52592737,
        -0.63393298, -0.88361972, -0.52592737,  1.3782406 ,  1.12942721,
         1.90140322, -0.72396752, -0.98632101,  1.90140322, -0.63943864,
         1.2273572 , -0.52592737, -0.79013171, -0.80874158, -0.52592737,
         1.25617071, -0.56297505, -1.1059698 ,  1.94458183, -0.52504733,
        -0.71102597, -0.54480692,  1.88720123]])

In [16]:
import numpy as np

In [17]:
a = Xmaria_normalizado

In [18]:
b = X_normalizado[0]

In [19]:
# 1 - começamos subtraindo
a-b

array([[-2.00115254,  0.        ,  3.3814487 ,  0.        ,  0.        ,
        -0.04072036,  0.3340212 ,  2.00139589, -3.3814487 ,  0.        ,
        -2.10545189,  2.01476153,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         2.42733059,  0.        , -2.00018971,  2.42733059,  0.        ,
         0.        ,  0.        ,  0.        , -2.0452305 ,  0.        ,
         2.05224086,  0.        , -2.01015362,  2.45883121,  0.        ,
        -2.11744436,  0.        ,  2.41708643]])

In [20]:
# 2 - depois realizamos a exponenciação
np.square(a-b)

array([[4.00461149e+00, 0.00000000e+00, 1.14341953e+01, 0.00000000e+00,
        0.00000000e+00, 1.65814802e-03, 1.11570160e-01, 4.00558550e+00,
        1.14341953e+01, 0.00000000e+00, 4.43292768e+00, 4.05926401e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        5.89193381e+00, 0.00000000e+00, 4.00075888e+00, 5.89193381e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.18296779e+00, 0.00000000e+00, 4.21169253e+00, 0.00000000e+00,
        4.04071758e+00, 6.04585093e+00, 0.00000000e+00, 4.48357062e+00,
        0.00000000e+00, 5.84230682e+00]])

In [21]:
# 3 - soma
np.sum(np.square(a-b))

84.07574038273466

In [22]:
# 4 - tiramos a raiz e temos nossa distância
np.sqrt(84.07574038273466)

9.169282435541762

#### Implementando o Modelo

In [23]:
# biblioteca para divisão dos dados
from sklearn.model_selection import train_test_split

In [24]:
X_treino, X_teste, y_treino, y_teste = train_test_split(X_normalizado, y, test_size=0.3, random_state=123)

In [25]:
# biblioteca para criarmos o modelo de machine learning
from sklearn.neighbors import KNeighborsClassifier

In [26]:
# instanciar o modelo (criar o modelo) - por padrão são 5 vizinhos
knn = KNeighborsClassifier(metric='euclidean')

In [27]:
# treinando o mdelo com os dados de treino
knn.fit(X_treino, y_treino)

KNeighborsClassifier(metric='euclidean')

In [28]:
# testando o modelo com os dados de teste
predito_knn = knn.predict(X_teste)

In [29]:
predito_knn

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

## Aula 3

In [30]:
# Utilizar mediana, proque é o valor central dos nossos dados ordenados
np.median(X_treino)

-0.5259273725834717

In [31]:
# biblioteca para criarmos o modelo de machine learning
from sklearn.naive_bayes import BernoulliNB

In [32]:
# criamos o modelo
bnb = BernoulliNB(binarize=0.44) # valores > 0.44 serão transformados em 1, valores < 0.44 serão transformados em 0

In [33]:
bnb.fit(X_treino, y_treino)

BernoulliNB(binarize=0.44)

In [34]:
predito_bnb = bnb.predict(X_teste)

In [35]:
predito_bnb

array([1, 0, 0, ..., 0, 1, 0], dtype=int64)

## Aula 4

In [36]:
from sklearn.tree import DecisionTreeClassifier

In [37]:
# instanciando o modelo
dtc = DecisionTreeClassifier(criterion='entropy', random_state=42)

In [38]:
# treinando o modelo
dtc.fit(X_treino, y_treino)

DecisionTreeClassifier(criterion='entropy', random_state=42)

In [39]:
# verificar a importância de cada atributo
dtc.feature_importances_

array([0.03168742, 0.01862901, 0.00064085, 0.02675693, 0.0208788 ,
       0.2056003 , 0.29546501, 0.0061786 , 0.00273035, 0.00747536,
       0.        , 0.04908356, 0.        , 0.01609395, 0.        ,
       0.00722833, 0.01220706, 0.        , 0.01248286, 0.01138295,
       0.0006673 , 0.0095669 , 0.01841631, 0.        , 0.00650511,
       0.00385849, 0.        , 0.00666929, 0.00517146, 0.        ,
       0.00665371, 0.00473251, 0.15803541, 0.00348686, 0.01414378,
       0.01601964, 0.01064163, 0.01091026])

In [40]:
predito_dtc = dtc.predict(X_teste)

In [41]:
predito_dtc

array([1, 0, 0, ..., 1, 0, 0], dtype=int64)

## Aula 5

#### Matrix de Confusão

In [42]:
from sklearn.metrics import confusion_matrix

In [43]:
print(confusion_matrix(y_teste, predito_knn))

[[1305  218]
 [ 317  273]]


In [44]:
print(confusion_matrix(y_teste, predito_bnb))

[[1059  464]
 [ 120  470]]


In [45]:
print(confusion_matrix(y_teste, predito_dtc))

[[1249  274]
 [ 290  300]]


#### Acurácia

In [46]:
from sklearn.metrics import accuracy_score as acc_score

In [47]:
print(acc_score(y_teste, predito_knn))

0.7468054898248935


In [48]:
print(acc_score(y_teste, predito_bnb))

0.7236157122574538


In [49]:
print(acc_score(y_teste, predito_dtc))

0.7330809275911027


#### Precisão

In [50]:
from sklearn.metrics import precision_score

In [51]:
print(precision_score(y_teste, predito_knn))

0.5560081466395111


In [52]:
print(precision_score(y_teste, predito_bnb))

0.5032119914346895


In [53]:
print(precision_score(y_teste, predito_dtc))

0.5226480836236934


#### Recall

In [54]:
from sklearn.metrics import recall_score

In [55]:
print(recall_score(y_teste, predito_knn))

0.46271186440677964


In [56]:
print(recall_score(y_teste, predito_bnb))

0.7966101694915254


In [57]:
print(recall_score(y_teste, predito_dtc))

0.5084745762711864
